### ISSUE TITLE
>>remind upgrades?

### ISSUE THREAD

**Issue by EverTokki** [abraker95/apex-sigma#19]
1. .>>remind <@ person> --> gives out a list of reminders the person has & amount of time left
2. make it so >>remind <time> <message with @ person> can highlight the other person..? Dunno if possible but this is not a necessary feature.

**Comment by abraker95** [comment]
Shouldn't it be applicable to yourself only? Seeing other's reminders is kinds creepy

**Comment by EverTokki** [comment]
yea sure, that makes sense

**Comment by abraker95** [comment]
Well this turns out to be a bit harder than I thought it would be. I was expecting the bot to put the reminder message and time into the database and recall it when needed, but it turns out that it's just a plain async sleep function instead. I don't think I can relay back the info of a frozen command. And if I could, it would prob involve some black magic I don't want to be bothered with. So far I think I would need to rework the command to put in the text and time and have it check every second or so. Though that's a polling type approach and I want an event trigger instead.

Also since it's just a plain async sleep function, idk if reminders still get sent after the bot goes down, so that might be counted as a bug when and if confirmed that they don't get sent.

**Comment by abraker95** [comment]
Implemented in sickle-2.0 branch
