### ISSUE TITLE
The roast command sometimes fails

### ISSUE THREAD

**Issue by abraker95** [abraker95/apex-sigma#64]
Gives this:
![](https://i.imgur.com/2G9GXSK.png)

**Comment by johnmedina999** [comment]
On Line 11 of [`roast.py`](https://github.com/abraker95/apex-sigma/blob/master/sigma/plugins/fun/roast.py), we have the following: `page_num = random.randint(0, 36)`. This is an issue, because the site only has pages from 1 to 31, and we shouldn't even use page 31 because it's not complete. This should be an easy fix by replacing Line 11 with `page_num = random.randint(1, 30)`.

**Comment by abraker95** [comment]
well that explains it
